#!/usr/bin/env python3

"""
Version1 
No setters and getters  
@author: abdishu
"""

import math

class Circle():
    def __init__(self, radius):
        self.radius = radius
    def get_diameter(self):
        return self.radius* 2
    def getRadius(self):   #This is getter of number
        return self.radius
    def area(self):
        return math.pi * (self.radius)**2
    def __str__(self):
        return "Circle with radius:" + str(format(self.radius, '.6f'))
    def __add__(self,other):
        return Circle(self.getRadius() + other.getRadius())
